namespace:
  name: sandbox
service:
  port: 4111
  protocol: TCP
  targetPort: 3111
  type: ClusterIP
image:
  repository: dungtest1000/techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
containerPort: 3111
livenessProbe:
  initialDelaySeconds: 1
  periodSeconds: 2
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 1
  path: /healthz
  port: 3111
readinessProbe:
  initialDelaySeconds: 1
  periodSeconds: 2
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 1
  path: /healthz
  port: 3111
